Repository gavv/httpexpect, pull requests merged in 2023-01, with the labels that each got.

#224 Add unit tests for chain cloning
  array_test.go
  boolean_test.go
  cookie_test.go
  datetime_test.go
  duration_test.go
  environment_test.go
  go.mod
  go.sum
  match_test.go
  number_test.go
  object_test.go
  response_test.go
  string_test.go
  value_test.go
  websocket_message_test.go
Labels: needs revision

#213 Added methods to enhance datetime class.
  datetime.go
  datetime_test.go
Labels: needs revision

#226 Add noCopy protection
  array.go
  boolean.go
  cookie.go
  datetime.go
  duration.go
  environment.go
  expect.go
  nocopy.go
  number.go
  object.go
  request.go
  response.go
  string.go
  websocket.go
Labels: needs revision

#221 Extend fruits server example
  _examples/fruits_test.go
Labels: needs revision

#223 Decode methods
  array.go
  array_test.go
  boolean.go
  boolean_test.go
  canon.go
  canon_test.go
  number.go
  number_test.go
  object.go
  object_test.go
  string.go
  string_test.go
Labels: work in progress

#230 Implement usage check for Expect in Request and Websocket
  request.go
  request_test.go
Labels: needs revision

#227 implement alias support
  README.md
  array.go
  array_test.go
  assertion.go
  boolean.go
  boolean_test.go
  chain.go
  chain_test.go
  cookie.go
  cookie_test.go
  datetime.go
  datetime_test.go
  duration.go
  duration_test.go
  e2e_report_test.go
  formatter.go
  match.go
  match_test.go
  number.go
  number_test.go
  object.go
  object_test.go
  response.go
  response_test.go
  string.go
  string_test.go
  value.go
  value_test.go
  websocket.go
  websocket_message.go
  websocket_message_test.go
  websocket_test.go
Labels: needs revision, needs rebase

#231 add example custom formatter
  README.md
  _examples/custom_formatter_test.go
  _examples/go.mod
  _examples/go.sum
Labels: needs revision

#238 Decode method
  README.md
  array.go
  boolean.go
  number.go
  object.go
  object_test.go
  string.go
  value.go
  value_test.go
Labels: needs revision, needs rebase
