Repository gavv/httpexpect, pull requests merged in 2023-03, with the labels that each got.

#312 refactor usage test to table driven
  request_test.go
Labels: ready for review

#314 Convert some number tests to be table driven
  number_test.go
Labels: ready for review

#316 Add tests for custom templates in DefaultFormatter
  formatter_test.go
Labels: ready for review

#313 Convert some DateTime and Duration tests to be table driven
  datetime_test.go
  duration_test.go
Labels: needs revision

#317 Unit test TestFormatter_FailureErrors
  assertion_test.go
  formatter.go
  formatter_test.go
  mocks_test.go
Labels: needs revision

#331 Convert String tests to table-driven style
  string_test.go
Labels: needs revision

#318 Support colored output
  assertion.go
  chain.go
  chain_test.go
  formatter.go
  formatter_test.go
  go.mod
  go.sum
Labels: ready for review

#332 function implementations for expect config
  expect.go
  expect_test.go
Labels: ready for review

#336 Implement colorization for formatted diffs
  formatter.go
Labels: ready for review

#323 Refactor TestRequest_Order to table driven
  request_test.go
Labels: needs revision

#338 Refactor and improve TestRequest_URLQuery
  mocks_test.go
  request_test.go
Labels: ready for review

#337 Add DefaultFormatter.EnableRequests and EnableResponses
  e2e_report_test.go
  formatter.go
Labels: ready for review, needs rebase

#340 Improved coverage for array and object test
  array_test.go
  object_test.go
Labels: ready for review

#333 feat: refactor requests into subtests
  request_test.go
Labels: needs revision

#348 [346]:...Refactor of datetime and duration test to use assertOK
  datetime_test.go
  duration_test.go
Labels: needs revision

#347 Refactor Number and String tests to use chain.assertOK
  number_test.go
  string_test.go
Labels: ready for review

#350 TestRequest_Websocket
  request_test.go
Labels: ready for review

#361 imp(environment): refactor unit test
  environment_test.go
Labels: ready for review
